### ISSUE TITLE
entity relations widget

### ISSUE THREAD

**Issue by jusa3** [nfdi4health/semlookp-widgets#29]
Create an entity relations widget as [here](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C2985):
![image](https://github.com/nfdi4health/semlookp-widgets/assets/91457824/6c61980d-23d7-4bed-875f-df2db813cc0c)

You can either
- move branch [feature-relations](https://gitlab.zbmed.de/km/semlookp/widgets-semlookp/-/tree/feat-relations) from GitLab to GitHub (don't know, why it wasn't moved with the project automatically). Was developed to work with ols3 but needs to be adapted to ols4 (please use the EBI API for testing), because we need the information in Manchester Syntax ([example](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000400)).   
![image](https://github.com/nfdi4health/semlookp-widgets/assets/91457824/b74ea1b4-c019-4a10-9f47-270780cad2bc)
- or start from scratch (you can have a look at the code of [ols4](https://github.com/EBISPOT/ols4)). Since recently they use React - maybe they have a better approach.

I'm not sure what informations exist (subclass of, related from ...) - maybe you can have a look at some entities. Do you have a complete list @rombaum ?

**Comment by VincentKneip** [comment]
There are many types of information such as:
- subclass of ([example](https://www.ebi.ac.uk/ols4/ontologies/bco/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBCO_0000031))
- related from ([example](https://www.ebi.ac.uk/ols4/ontologies/bco/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBCO_0000031))
- equivalent to ([example](https://www.ebi.ac.uk/ols4/ontologies/bco/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBCO_0000047))
- disjoint with ([example](https://www.ebi.ac.uk/ols4/ontologies/bfo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000004))
- inverse of ([example](https://www.ebi.ac.uk/ols4/ontologies/agro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050))
- property chain ([example](https://www.ebi.ac.uk/ols4/ontologies/agro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000062))

A complete List of all entityPageSections can be found by looking into [this](https://github.com/EBISPOT/ols4/tree/dev/frontend/src/pages/ontologies/entities/entityPageSections) directory of the OLS4 repository. Every file implements one section.

**Comment by jusa3** [comment]
Then starting with the ols4 component/code might be a better option.

**Comment by julian-schneider** [comment]
If we wanted to use their element 1:1 in SemLookP, we could widgetize their code and plop it into this project. But the styles wouldn't match, sadly. I think this is a smaller issue for the EntityTreeWidget than it would be for the relations widget.

**Comment by VincentKneip** [comment]
Yes, I will start with looking at the ols4 code. By the way, the code for the Relations widget in ols4 can be found [here](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/pages/ontologies/entities/EntityPage.tsx#L434-L483).

**Comment by VincentKneip** [comment]
Some information displayed in the relations widget is contained directly in the entity's JSON, like parents for subtypes or types for individual type ([example](https://www.ebi.ac.uk/ols4/ontologies/agro/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FENVO_01001569)). Unfortunately though, this is not always the case, like for different from for individuals ([example](https://www.ebi.ac.uk/ols4/ontologies/bco/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FIAO_0000120)). Therefore, fetching the data from the JSON won't be an option.

In ols4, the information lies in a properties attribute (type any, so I don't really know what this is) of the class [Thing](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/model/Thing.ts#L6) and its subclasses Entity, Class, Individual etc. (located in the same folder), which is treated like some kind of array. For example, to retrieve the types of an individual, [this function](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/model/Thing.ts#L51-L55) is used.

The entities are accessed via an [ontologies slice](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/pages/ontologies/ontologiesSlice.ts) which is incorporated in a [React redux store reducer](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/app/store.ts) via the [useSelector](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/pages/ontologies/entities/EntityPage.tsx#L62-L68) hook.

Implementing all of this in semlookp-widgets seems a bit too much for a single widget. Can some else maybe have a look on how we can extract the sections information with a simpler and more suitable method for semlookp-widgets?

**Comment by julian-schneider** [comment]
We found out that the v2 API appears to contain all of the types displayed in the OLS4 frontend ([example](https://www.ebi.ac.uk/ols4/api/v2/ontologies/bco/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FIAO_0000120)), so it can be extracted from the JSON.

**Comment by jusa3** [comment]
Looks good so far. I would prefer letting useQuery save the response, because it's less time consuming querying once compared to querying for every section.

If it becomes unclear/too much code you can think about creating sub-components. The widget does not have to consist of only one component.

btw there is a new endpoint in the ols4 API, that is not yet in the documentation but will be with the release.
https://www.ebi.ac.uk/ols4/api/v2/ontologies/ncit/entities?iri=http:%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C2984
or
https://www.ebi.ac.uk/ols4/api/v2/entities?iri=http:%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C2984
with the key "entites" instead class/term/property/individual. I didn't look into the information you get yet but maybe this may help a bit with optimization of the code.

**Comment by VincentKneip** [comment]
Done! `useQuery` now [just saves the response](https://github.com/nfdi4health/semlookp-widgets/blob/entity-relations-widget/src/components/widgets/EntityRelationsWidget/EntityRelationsWidget.tsx#L171-L187). The sections are realized as pseudo sub-components at the moment (extracting the information in a [function](https://github.com/nfdi4health/semlookp-widgets/blob/entity-relations-widget/src/components/widgets/EntityRelationsWidget/EntityRelationsWidget.tsx#L106-L169) which then returns the `JSX` element for the section).

I did not look into the new endpoint yet, however my goal so far is to do as few api calls as possible. For now, only one call (the one for the respective entity) suffices.

Hyperlinks and labels are now available for subclass of and different from. The links for now lead to the respective iri url, but should probably lead to the respective semlookp pages later.

A first experiment with the Manhattan syntax is now pushed (see [here](https://github.com/nfdi4health/semlookp-widgets/blob/entity-relations-widget/src/components/widgets/EntityRelationsWidget/EntityRelationsWidget.tsx#L39-L78)). However, not everything is covered yet (e.g. `only` keyword, for which I did not find an example entity yet).

**Comment by julian-schneider** [comment]
Could the API method `ols4/api/v2/ontologies/ID/entities` be used instead of the logic in `getEntityJson()`? That should not require more requests.

And yeah, it would be handy if the hyperlinks lead to semlookp pages. But what if the entity is not hosted on semlookp at all, that can happen right? Either the links point to different locations, depending on whether their target is hosted by semlookp, which might be confusing. Or there are multiple clickables - How about something like this:
![image](https://github.com/nfdi4health/semlookp-widgets/assets/130765495/e70368b9-ce17-4a17-8394-0a748923de5c)
Where the label hyperlink always points to the IRI, and if the entity exists in semlookp, the extra bubble is added and points to the semlookp entity page.

**Comment by VincentKneip** [comment]
#

> Could the API method `ols4/api/v2/ontologies/ID/entities` be used instead of the logic in `getEntityJson()`? That should not require more requests.
> 
> And yeah, it would be handy if the hyperlinks lead to semlookp pages. But what if the entity is not hosted on semlookp at all, that can happen right? Either the links point to different locations, depending on whether their target is hosted by semlookp, which might be confusing. Or there are multiple clickables - How about something like this: ![image](https://user-images.githubusercontent.com/130765495/268222087-e70368b9-ce17-4a17-8394-0a748923de5c.png) Where the label hyperlink always points to the IRI, and if the entity exists in semlookp, the extra bubble is added and points to the semlookp entity page.

`ols4/api/v2/ontologies/ID/entities` is now [used](https://github.com/nfdi4health/semlookp-widgets/commit/babb23b82f8aa833d1f63d827faa3989c72bc425) instead of the logic in `getEntityJson()`.

**Regarding the hyperlinks** 
The label hyperlink in EBI OLS references the EBI OLS page of the specific entity inside the ontology of the _currently viewed entity_. The badges reference the EBI OLS page of the specific entity inside its _defining ontology_. If the defining ontology is the same as the ontology of the currently viewed entity, no badge is shown, if the entity is defined in multiple ontologies, multiple badges can be shown.

Since the ontologies of SemLookP will be limited, it would probably be better to make the label reference the iri-URL because the SemLookP-page might not exist. If pages exist, differently colored Badges for currently viewed and defining ontologies could be shown.

What do think of this idea @rombaum ? How do you imagine the look and functionality of the widget?

**Comment by VincentKneip** [comment]
Almost everything is done by now. A demonstration of different scenarios can be found in Storybook. 
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/5e5c8eb8-ad8f-4941-bc89-52fed3fe3eab)

Three major parts remain:

1. How should the widgets' appearance be?
2. Where should the hyperlinks redirect to/ what badges do we want? (see comment [above](https://github.com/nfdi4health/semlookp-widgets/issues/29#issuecomment-1723833773))
3. What does [onDataType](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/components/ClassExpression.tsx#L183-L235) do in Manchester syntax?

**Comment by jusa3** [comment]
Well done!

The widgets appearance: since the new SemLookP app does not have any style yet, I would keep this widget as simple as it is for now. Questions 2. and 3. @rombaum 

Please add error handling if the API request can't be resolved (e.g if the terminology is not available) - at least an error event. Maybe also some information for the user of the website e.g. "Terminology not available" or sth. else. 
See https://www.ebi.ac.uk/ols4/api/v2/ontologies/mesh/entities?iri=http:%2F%2Fpurl.bioontology.org%2Fontology%2FMESH%2FD004194 (IRI: http://purl.bioontology.org/ontology/MESH/D004194)

**Comment by VincentKneip** [comment]
Error handling is included now by [throwing an error](https://github.com/nfdi4health/semlookp-widgets/commit/4184fe4c52d4638b050b96bb1a5e66ad1936c5ea#diff-76b4c1e7fe58a3bc6839d04316465f27ae0671a8ccba68b71a2d50b654039d6dR549-R554) in the `useQuery()` `queryFn` when `response["elements"][0]` is undefined:
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/f43f7317-243a-4436-a709-99dc2c6e48a0)

`useQuery()` `isError` then helps to [render an error message](https://github.com/nfdi4health/semlookp-widgets/commit/4184fe4c52d4638b050b96bb1a5e66ad1936c5ea#diff-76b4c1e7fe58a3bc6839d04316465f27ae0671a8ccba68b71a2d50b654039d6dR602) inside the widget:
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/0e59f470-a65f-4556-8f11-410b072613a1)

**Comment by jusa3** [comment]
There are other reasons for the entity not beeing resolved, too (e.g. wrong entity type). The error message inside the widget should be more general. How about "Requested resource not available"?

**Comment by VincentKneip** [comment]
Wrong entity types don't make a difference anymore since the widget is now using the universal `ols4/api/v2/ontologies/ID/entities` route. But the api server being down would be another reason, so you're right. The error message is now changed:

![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/c51ee2e1-aae1-4f69-a16d-89c543bf5873)

**Comment by VincentKneip** [comment]
**Regarding onDataType:**
The label `"http://www.w3.org/2002/07/owl#onDatatype"` only seems to occur within `"http://www.w3.org/2000/01/rdf-schema#range"` used in the [RangeSection](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/pages/ontologies/entities/entityPageSections/RangeSection.tsx), defining value restrictions ([example](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002029)). However, RangeSection is only part of the [Information](https://github.com/EBISPOT/ols4/blob/dev/frontend/src/pages/ontologies/entities/EntityPage.tsx#L407-L430), not the Relations section which the widget represents.

But with this comes the question: Should the EntityInfoWidget of SemLookP be modified to show all the info displayed on the Information section of OLS?

**Comment by jusa3** [comment]
All widgets (except relations widget and hierarchy widget) must work with the ols3 API. If this info can be retrieved from the ols3 API then yes. The implementation gets a bit more complex if it's only available in the ols4 API. We would need a condition based on the use of the API version and documentation.

I opened two more issues #30 and #31 that can be prioritized.

**Comment by VincentKneip** [comment]
No, the information does not seem to be available in ols3. Do we then still want to include it?

**Comment by jusa3** [comment]
Maybe let's first do the metadata widget refactoring to get a feeling on how complex the switch between ols3 and ols4 will be (because we have the requirement of users for the metadata widget to get it to work with the IRI only -> needs ols4).

**Comment by rombaum** [comment]
First of all. @VincentKneip Nice Work! 

>     2. Where should the hyperlinks redirect to/ what badges do we want? (see comment [above](https://github.com/nfdi4health/semlookp-widgets/issues/29#issuecomment-1723833773))
> 

To answer this question I will use your example from the storybook. From my perspective if the entity is in SemLookP it should be used as target of the link. This is defined under the key linkedEntities in the [JSON](https://www.ebi.ac.uk/ols4/api/v2/ontologies/agro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FAGRO_00000002). The badge should be a optional parameter in the widget. By default it should be hidden. The parameter could named "show_badge". The data of the badge will only appear if the other ontology is loaded to ZB MED. If this is not the case we should use the purl as the target link.

**Comment by VincentKneip** [comment]
I also found an [info button](https://www.ebi.ac.uk/ols4/ontologies/aism/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000006) on the ols4 relations widget not incorporated in our relations widget yet:
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/f0224fd2-4125-4e70-8e35-29c8b0ba3e47)
It seems to be rendered whenever the key _axioms_ is provided in the JSON:
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/f7388769-b514-42e2-8115-fe6286d5ceeb)

Do we want to have this on our relations widget as well?

**Comment by jusa3** [comment]
What is the status? Can we merge? @VincentKneip @rombaum 

As a last step please test the widget with following API: http://ols4.qa.km.k8s.zbmed.de/ols4/api/v2/ @VincentKneip 

Have a look into the available ontologies: http://ols4.qa.km.k8s.zbmed.de/ols4/api/v2/ontologies/

**Comment by VincentKneip** [comment]
Implemented the suggestions of @rombaum. Badges can now be turned on and off using the property `showBadges: boolean` (provided $\Leftrightarrow$ badges are shown) and look like this:

Our EntityRelationsWidget for `UBERON_0000006` | EMBL-EBI ols4 Relations Section for `UBERON_0000006`
---------|---------
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/a8802059-3141-42ef-8fb2-88e0a6b1a419) | ![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/41ef854d-36cc-450f-b849-c88a985e1fb0)

Badges are shown for definitions of an entity within ontologies other than the local ontology (the one you're currently in) and link to the API's frontend page of the entity in the respective ontology.

The label of the entity links to (see [here](https://github.com/nfdi4health/semlookp-widgets/blob/588a592323b0e89ebe37ae649340426527ba22f2/src/components/widgets/EntityRelationsWidget/EntityRelationsWidget.tsx#L106-L237) for more information)
- the API's frontend page of the entity in the local ontology `if(hasLocalDefinition == true)`
- the API's frontend page of the entity in the first of the other defining ontologies `if(definedBy !== undefined)`
- the raw IRI `else`

**Comment by VincentKneip** [comment]
To be convenient with the other SemLookP widgets, the EntityRelationsWidget also gets passed the `api` without `v2` (e.g. `http://ols4.qa.km.k8s.zbmed.de/ols4/api/` instead of `http://ols4.qa.km.k8s.zbmed.de/ols4/api/v2/`) now and adds `v2` internally afterwards.

**Comment by VincentKneip** [comment]
>     @jusa3 After this we could merge the branch.
> 

Some TODOs (e.g. disambiguation page) still remain, but the requirements of @rombaum should now be fulfilled. The branch should therefore be able to be merged for now.
