### ISSUE TITLE
AutoCompleteWidget Multi Select breaks if multiple entries if same label exist

### ISSUE THREAD

**Issue by johannes-darms** [nfdi4health/semlookp-widgets#45]
I only selected MeSH but EFO is also selected in the dropdown.
<img width="1347" alt="Screenshot 2023-12-20 at 12 19 26" src="https://github.com/nfdi4health/semlookp-widgets/assets/8245181/f7686fe4-a5fd-4b4e-8b97-4acb3f415a73">

**Comment by VincentKneip** [comment]
Assigned the option's `iri` as `EuiComboBoxOption` property `key` to distinguish options with the same label (see https://github.com/nfdi4health/semlookp-widgets/commit/aab6bec9bd777d155979e08659f706956c436584). This is the strategy [recommended by Elastic](https://eui.elastic.co/#/forms/combo-box#duplicate-labels) when dealing with duplicate labels.

Now, only the clicked label is selected:
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/0d9c1c1c-84dd-4fe3-a297-0aaf68e1cafe)
