### ISSUE TITLE
AutocompleteWidget: selectOption

### ISSUE THREAD

**Issue by VincentKneip** [nfdi4health/semlookp-widgets#49]
As selecting multiple options is now supported, should `selectOption` be changed into an array of options to possibly provide multiple pre-selected values? If so, it has to be decided how to handle multiple options in `selectOption` if `singleSelection == true`.

**Comment by jusa3** [comment]
Do you need multiple pre-selected values? @johannes-darms

**Comment by johannes-darms** [comment]
Yes!

**Comment by VincentKneip** [comment]
If multiple `selectOptions` can be provided, what should happen if multiple options are provided while `singleSelection == true`? Should it just select the first one and ignore the rest? @johannes-darms

**Comment by johannes-darms** [comment]
That would be an invalid invariant. Either the component fails due the logical error or some document correction behaviour, as you suggested, is implemented. It's your decision, I'm happy with both implementations. 

Is the signature of the component the same for single or multiple selection?

**Comment by VincentKneip** [comment]
Ok, then I choose the correction behaviour of just selecting the first of `selectOption` as it provides more convenience when switching between single and multiple selection.

And yes, the widgets' signature is the same for both selection styles. An additional component property `singleSelection` (boolean) can be provided to control the selection style.

As `selectOption` will be converted into an array, but the word `selectOption` suggests one singular value, I would also prefer to rename the property to `preselected` as this does not suggest a certain numerus (singular or plural) as this can semantically change depending on the value of `singleSelection`
